services:
  web-controller-api:
    build:
      context: .
      dockerfile: WebControllerApi/Dockerfile
    container_name: my-api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081

  web-minimal-api:
    build:
     context: .
     dockerfile: WebMinimalApiAOT/Dockerfile
    ports:
      - "5002:8080"
volumes:
  postgres-data:
